spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application: 
    name: microservercloud-config-guoyr-test
---
spring:
  profiles: test
  application: 
    name: microservercloud-config-guoyr-test
#请保存为UTF-8格式
