spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001 #注册中心占用7001端口,冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name : microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01    #数据库名
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                 #数据库连接池最小维持连接数
      initial-size: 5                             #初始化连接数
      max-total: 5                                #最大连接数
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.guoyr.cloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务器名称信息
    prefer-ip-address: true
info:
  app.name: guoyr-microservicecloud
  company.name: www.guoyr.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$